/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.18
 * Generated at: 2022-03-17 11:54:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class report_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<h3>\r\n");
      out.write("			<br><br><center>All Employees Details</center>\r\n");
      out.write("		</h3>\r\n");
      out.write("		<br>\r\n");
      out.write("		<center>\r\n");
      out.write("			<table style=\"text-align: center;\">\r\n");
      out.write("			  <tr style=\"text-align: center;\">\r\n");
      out.write("			    <th>Emp_id_num</th>\r\n");
      out.write("			    <th>First Name</th>\r\n");
      out.write("			    <th>Last Name</th>\r\n");
      out.write("			    <th>DOB</th>\r\n");
      out.write("			    <th>Contact</th>\r\n");
      out.write("			  </tr>\r\n");
      out.write("			  <tr>\r\n");
      out.write("			    <td>1</td>\r\n");
      out.write("			    <td>Adarsh</td>\r\n");
      out.write("			    <td>Singh</td>\r\n");
      out.write("			    <td>01/01/2000</td>\r\n");
      out.write("			    <td>8957973232</td>\r\n");
      out.write("			  </tr>\r\n");
      out.write("			  <tr>\r\n");
      out.write("			    <td>102</td>\r\n");
      out.write("			    <td>Shivam</td>\r\n");
      out.write("			    <td>Dubey</td>\r\n");
      out.write("			    <td>17/11/2004</td>\r\n");
      out.write("			    <td>8954678954</td>\r\n");
      out.write("			  </tr>\r\n");
      out.write("			  <tr>\r\n");
      out.write("			    <td>105</td>\r\n");
      out.write("			    <td>Adam</td>\r\n");
      out.write("			    <td>Clive</td>\r\n");
      out.write("			    <td>19/11/2002</td>\r\n");
      out.write("			    <td>6789567809</td>\r\n");
      out.write("			  </tr>\r\n");
      out.write("			  <tr>\r\n");
      out.write("			    <td>110</td>\r\n");
      out.write("			    <td>mike</td>\r\n");
      out.write("			    <td>Tison</td>\r\n");
      out.write("			    <td>08/11/2009</td>\r\n");
      out.write("			    <td>2345674365</td>\r\n");
      out.write("			  </tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</center>\r\n");
      out.write("		\r\n");
      out.write("		<br><br>\r\n");
      out.write("		<center>Enter Employee_Id to show details:\r\n");
      out.write("		<input type=\"text\" name=\"id\">\r\n");
      out.write("		<input type=\"submit\" name=\"show\" value=\"Show Report\"></center><br>\r\n");
      out.write("		\r\n");
      out.write("		<center>\r\n");
      out.write("			<table style=\"text-align: center;\">\r\n");
      out.write("			  <tr style=\"text-align: center;\">\r\n");
      out.write("			    <th>Emp_id_num</th>\r\n");
      out.write("			    <th>First Name</th>\r\n");
      out.write("			    <th>Last Name</th>\r\n");
      out.write("			    <th>DOB</th>\r\n");
      out.write("			    <th>Contact</th>\r\n");
      out.write("			    <th>Job Role</th>\r\n");
      out.write("			    <th>Salary</th>\r\n");
      out.write("			    <th>Yearly Bonus</th>\r\n");
      out.write("			  </tr>\r\n");
      out.write("			  <tr>\r\n");
      out.write("			    <td>1</td>\r\n");
      out.write("			    <td>adarsh</td>\r\n");
      out.write("			    <td>singh</td>\r\n");
      out.write("			    <td>15/07/2000</td>\r\n");
      out.write("			    <td>8957973232</td>\r\n");
      out.write("			    <td>SDE</td>\r\n");
      out.write("			    <td>800000</td>\r\n");
      out.write("			    <td>900000</td>\r\n");
      out.write("			  </tr>\r\n");
      out.write("				  \r\n");
      out.write("			</table>\r\n");
      out.write("		</center>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
